name: 'ci'

on:
  push

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build docker
        run: ./build-docker

      - name: run docker
        run: ./run-docker
