name: 'ci'

on:
  push

jobs:
  docker-base:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build docker
        run: ./build-docker

  install-zsh:
    runs-on: automatic-setup
    steps:
      - name: test
        run: echo success
