name: 'ci'

on:
  push

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: initial
        run: echo "Here you are"

      - name: docker test
        run: docker run -t ubuntu bash -c "which whichhhh"
