name: 'ci'

on:
  push

jobs:
  docker-base:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build docker
        run: ./build-docker

  install-zsh:
    needs: docker-base
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run docker
        run: ./run-docker
