name: 'ci'

on:
  push

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build docker
        run: docker build . -t automatic-setup

      - name: run docker
        run: docker run -t automatic-setup bash -c "echo success"
